baseURL = 'https://tvvcc.org/'
languageCode = 'en-us'
title = 'Treasure Valley Vintage Computer Club'
theme = 're-terminal'

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  [params.banner]
    dismissible = true
    text = "Join our Discord!"
    url = "https://discord.gg/Kb6atM39"

[languages]
  [languages.en.params]
    title = "Treasure Vally Vintage Computing Club"
    subtitle = "Boise's premiere vintage computing club."
    keywords = "Boise, retro, vintage, computer, computing, electronics"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Treasure Vally Vintage Computing Club"
      logoHomeLink = "/"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "submenu"
    name = "Workbench"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "subabout"
    name = "About"
    url = "/about"
    parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"